//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed
//four million, find the sum of the even-valued terms.
var fibbonoci = {
  fibbo: function() {
    var first = 1, second = 2, i= 0, j=0, k=0;
    console.log(first);
    console.log(second);
    while (j < 10){
        j +=1;
        i = first + second;
        // console.log(i);
        first = second;
        second = i;

        if (i % 2 == 0)
        {
         i = i + k;
         k = i;
       }
    }
    //
    console.log("Total value of even number ", k);

  }
};
fibbonoci.fibbo();
